# Light EM Augmentation Preset
# Use case: Quick experiments, large datasets, fast iteration
# Training speed: Fast (minimal overhead)
# Model robustness: Basic

system:
  num_gpus: 1
  num_cpus: 4
  seed: 42

model:
  architecture: monai_basic_unet3d
  in_channels: 1
  out_channels: 2
  filters: [32, 64, 128, 256, 512]
  dropout: 0.1

  loss_functions:
    - DiceLoss
    - BCEWithLogitsLoss
  loss_weights: [1.0, 1.0]

data:
  # Data paths (modify for your dataset)
  train_image: "datasets/lucchi/train_image.h5"
  train_label: "datasets/lucchi/train_label.h5"
  val_image: "datasets/lucchi/val_image.h5"
  val_label: "datasets/lucchi/val_label.h5"

  patch_size: [128, 128, 128]
  batch_size: 2
  num_workers: 4

  # Light augmentation strategy
  augmentation:
    use_augmentation: true
    transforms:
      # Missing sections (low probability)
      - RandMissingSectiond:
          keys: ["image"]
          prob: 0.3
          num_sections: 1

      # Misalignment (translation only, low probability)
      - RandMisAlignmentd:
          keys: ["image"]
          prob: 0.3
          displacement: 8
          rotate_ratio: 0.0  # Translation only (faster)

      # Standard MONAI transforms (optional, can be added)
      # - RandShiftIntensityd:
      #     keys: ["image"]
      #     prob: 0.3
      #     offsets: 0.1

optimizer:
  name: AdamW
  lr: 1e-4
  weight_decay: 1e-4

scheduler:
  name: CosineAnnealingLR
  warmup_epochs: 5

training:
  max_epochs: 100
  precision: "16-mixed"
  gradient_clip_val: 1.0

checkpoint:
  monitor: "val/loss"
  mode: "min"
  save_top_k: 3
  save_last: true

logging:
  log_every_n_steps: 50
  save_dir: "outputs"
