cfg:
  experiment_name: lucchi++_monai_unet
  description: Mitochondria segmentation on Lucchi++ EM dataset using MONAI Residual
    UNet
  system:
    training:
      num_gpus: 4
      num_cpus: 8
      num_workers: 8
      batch_size: 32
    inference:
      num_gpus: 1
      num_cpus: 1
      num_workers: 1
      batch_size: 32
    seed: 42
    auto_plan: false
    print_auto_plan: true
  model:
    architecture: monai_unet
    input_size:
    - 112
    - 112
    - 112
    output_size:
    - 112
    - 112
    - 112
    in_channels: 1
    out_channels: 2
    filters:
    - 28
    - 36
    - 48
    - 64
    - 80
    dropout: 0.1
    norm: batch
    num_groups: 8
    activation: relu
    spatial_dims: 3
    num_res_units: 2
    kernel_size: 3
    strides: null
    act: relu
    feature_size: 16
    hidden_size: 768
    mlp_dim: 3072
    num_heads: 12
    mednext_size: S
    mednext_base_channels: 32
    mednext_exp_r: 4
    mednext_kernel_size: 3
    mednext_do_res: true
    mednext_do_res_up_down: true
    mednext_block_counts:
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    mednext_checkpoint_style: null
    mednext_norm: group
    mednext_dim: 3d
    mednext_grn: false
    rsunet_norm: batch
    rsunet_activation: relu
    rsunet_num_groups: 8
    rsunet_down_factors: null
    rsunet_depth_2d: 0
    rsunet_kernel_2d:
    - 1
    - 3
    - 3
    rsunet_act_negative_slope: 0.01
    rsunet_act_init: 0.25
    deep_supervision: false
    loss_functions:
    - DiceLoss
    - CrossEntropyLoss
    loss_weights:
    - 1.0
    - 0.5
    loss_kwargs:
    - include_background: false
      softmax: true
      to_onehot_y: true
      smooth_nr: 1.0e-05
      smooth_dr: 1.0e-05
    - label_smoothing: 0.1
    multi_task_config: null
  data:
    dataset_type: null
    train_image: datasets/Lucchi++/train_im.h5
    train_label: datasets/Lucchi++/train_mito.h5
    val_image: null
    val_label: null
    test_image: null
    test_label: null
    train_json: null
    val_json: null
    test_json: null
    train_image_key: images
    train_label_key: masks
    val_image_key: images
    val_label_key: masks
    test_image_key: images
    test_label_key: masks
    train_val_split: null
    patch_size:
    - 112
    - 112
    - 112
    pad_size:
    - 8
    - 8
    - 8
    stride:
    - 1
    - 1
    - 1
    train_resolution:
    - 5.0
    - 5.0
    - 5.0
    test_resolution: null
    target_spacing: null
    median_shape: null
    split_enabled: false
    split_train_range:
    - 0.0
    - 0.8
    split_val_range:
    - 0.8
    - 1.0
    split_axis: 0
    split_pad_val: true
    split_pad_mode: reflect
    pin_memory: true
    persistent_workers: true
    use_cache: false
    cache_rate: 1.0
    image_transform:
      normalize: 0-1
      clip_percentile_low: 0.0
      clip_percentile_high: 1.0
    iter_num_per_epoch: 1280
    use_preloaded_cache: true
    label_transform:
      normalize: true
      erosion: 0
      affinity:
        offsets: []
      skeleton_distance:
        enabled: false
        resolution:
        - 1.0
        - 1.0
        - 1.0
        alpha: 0.8
        smooth: true
        bg_value: -1.0
      keys:
      - label
      stack_outputs: true
      retain_original: false
      output_dtype: float32
      output_key_format: '{key}_{task}'
      allow_missing_keys: false
      segment_id: null
      boundary_thickness: 1
      targets: []
    augmentation:
      enabled: true
      flip:
        enabled: true
        prob: 0.5
        spatial_axis: null
      rotate:
        enabled: true
        prob: 0.5
        max_angle: 90.0
      elastic:
        enabled: true
        prob: 0.3
        sigma_range:
        - 5.0
        - 8.0
        magnitude_range:
        - 50.0
        - 150.0
      intensity:
        enabled: true
        gaussian_noise_prob: 0.3
        gaussian_noise_std: 0.05
        shift_intensity_prob: 0.3
        shift_intensity_offset: 0.1
        contrast_prob: 0.3
        contrast_range:
        - 0.7
        - 1.4
      misalignment:
        enabled: true
        prob: 0.5
        displacement: 16
        rotate_ratio: 0.0
      missing_section:
        enabled: true
        prob: 0.3
        num_sections: 2
      motion_blur:
        enabled: true
        prob: 0.3
        sections: 2
        kernel_size: 11
      cut_noise:
        enabled: false
        prob: 0.5
        length_ratio: 0.25
        noise_scale: 0.2
      cut_blur:
        enabled: true
        prob: 0.3
        length_ratio: 0.25
        down_ratio_range:
        - 2.0
        - 8.0
        downsample_z: false
      missing_parts:
        enabled: true
        prob: 0.5
        hole_range:
        - 0.1
        - 0.3
      mixup:
        enabled: true
        prob: 0.5
        alpha_range:
        - 0.7
        - 0.9
      copy_paste:
        enabled: true
        prob: 0.5
        max_obj_ratio: 0.7
        rotation_angles:
        - 30
        - 60
        - 90
        - 120
        - 150
        - 180
        - 210
        - 240
        - 270
        - 300
        - 330
        border: 3
  optimization:
    max_epochs: 1000
    max_steps: null
    gradient_clip_val: 1.0
    accumulate_grad_batches: 1
    precision: bf16-mixed
    deterministic: false
    benchmark: true
    val_check_interval: 1.0
    log_every_n_steps: 50
    optimizer:
      name: AdamW
      lr: 0.002
      weight_decay: 0.01
      momentum: 0.9
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
    scheduler:
      name: CosineAnnealingLR
      warmup_epochs: 10
      warmup_start_lr: 0.0001
      min_lr: 1.0e-06
      t_max: 950
      mode: min
      patience: 10
      factor: 0.5
      threshold: 0.0001
      cooldown: 0
      monitor: val_loss_total
      step_size: 30
      gamma: 0.1
  monitor:
    detect_anomaly: false
    logging:
      scalar:
        loss:
        - train_loss_total_epoch
        loss_every_n_steps: 10
        val_check_interval: 1.0
        benchmark: true
      images:
        enabled: true
        max_images: 8
        num_slices: 2
        log_every_n_epochs: 1
        channel_mode: argmax
        selected_channels: null
    checkpoint:
      monitor: train_loss_total_epoch
      mode: min
      save_top_k: 1
      save_last: true
      save_every_n_epochs: 10
      dirpath: outputs/lucchi++_monai_unet/checkpoints/
      checkpoint_filename: null
      use_timestamp: true
    early_stopping:
      enabled: true
      monitor: train_loss_total_epoch
      patience: 300
      mode: min
      min_delta: 1.0e-05
      check_finite: true
      threshold: 0.01
      divergence_threshold: 2.0
  inference:
    data:
      test_image: datasets/Lucchi++/test_im.h5
      test_label: datasets/Lucchi++/test_mito.h5
      test_resolution:
      - 5.0
      - 5.0
      - 5.0
      output_path: outputs/lucchi++_monai_unet/results/
    sliding_window:
      window_size:
      - 112
      - 112
      - 112
      sw_batch_size: null
      overlap: 0.5
      blending: gaussian
      sigma_scale: 0.25
      padding_mode: reflect
    test_time_augmentation:
      enabled: true
      flip_axes: all
      act: sigmoid
      select_channel: null
      ensemble_mode: mean
    postprocessing:
      output_scale: 255.0
      output_dtype: uint8
    evaluation:
      enabled: true
      metrics:
      - jaccard
    num_gpus: -1
    num_cpus: -1
    batch_size: -1
    num_workers: -1
