name: Tests

on:
  push:
    branches: [ main, master, v2.0 ]
  pull_request:
    branches: [ main, master, v2.0 ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -e .

    - name: Run tests
      run: |
        pytest tests/ -v --cov=connectomics --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install linters
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort mypy

    - name: Run black
      run: black --check connectomics/

    - name: Run flake8
      run: flake8 connectomics/ --max-line-length=100

    - name: Run isort
      run: isort --check connectomics/

    - name: Run mypy
      run: mypy connectomics/ --ignore-missing-imports
